"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u=+#@wc+m9zd@0c(k74pr-m9m0etkk&x5kih^-kkm9(a(847vg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'conexionrailway-production.up.railway.app',
    'localhost',  # Para pruebas locales, si es necesario
    '127.0.0.1',  # Para pruebas locales, si es necesario
]

AUTH_USER_MODEL = 'login_app.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Se agregan las apps de autenticación
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
 
    # Se agregan las apps de autenticación por redes sociales
    'allauth.socialaccount.providers.google',
    
    #apps propias
    'login_app',

    # Se agrega la app de Django Rest Framework
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',

    # Para permitir peticiones de otros dominios
    'corsheaders', 

    'drf_yasg',  # Para la documentación de la API
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Middleware para CORS
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'contenidos_ia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'contenidos_ia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS':{
            'max_similarity': 0.7, #evita que la contraseña se parezca al usuario, email, etc
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS':{
            'min_length': 12, #mínimo de caracteres OWASP recomienda 12
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'login_app.validators.ComplexityPasswordValidator',
    },
    
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
#STATICFILES_DIRS = [BASE_DIR / 'static']  # Directorio de archivos estáticos
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Definición hacia donde se redirige el usuario al loguearse o desloguearse

SITE_ID = 1 # Se define el id del sitio

LOGIN_REDIRECT_URL = '/home'
LOGOUT_REDIRECT_URL = '/login/'
LOGIN_URL = '/login/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Se define que la sesión expira al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Se define que la sesión expira en 30 minutos
SESSION_COOKIE_AGE = 3600
SESSION_SAVE_EVERY_REQUEST = True # Se guarda la sesión en cada request


# Se define la configuración de Django Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# JWT Authentication settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'BLACKLIST_AFTER_ROTATION': True,
}

# Permitir el dominio del frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # dominio del frontend local
    # "https://frontend.miempresa.com",  ← agregar cuando esté en producción
]

# Configuración para desarrollo: emails en la consola
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@miempresa.com'  # nombre identificativo

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': "Token JWT. Formato: **Bearer &lt;tu_token&gt;**",
        }
    },
}

CSRF_TRUSTED_ORIGINS = [
    'https://conexionrailway-production.up.railway.app',
]

SESSION_COOKIE_SECURE = True  # Usa True en producción con HTTPS
CSRF_COOKIE_SECURE = True    # Usa True en producción con HTTPS
CSRF_COOKIE_SAMESITE = 'Lax' # O 'Strict', dependiendo de tus necesidades